# Generated by Django 4.2.7 on 2023-11-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hockey_league', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='opponent_1_id',
            new_name='opponent_1_name',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='opponent_2_id',
            new_name='opponent_2_name',
        ),
    ]
